In [2]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.6 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

#Importing Libraries

In [26]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GroupShuffleSplit

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix,
    matthews_corrcoef,
    balanced_accuracy_score,
    brier_score_loss
)

from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
import random

In [7]:
random.seed(42)

# Load and Split dataset into train and test set

In [8]:
ckd_df = pd.read_csv("/content/CKD_preprocessed.csv")

ckd_X = ckd_df.drop("d_status", axis=1)
ckd_y = ckd_df["d_status"]

In [9]:
ckd_X_train, ckd_X_test, ckd_y_train, ckd_y_test = train_test_split(
    ckd_X,
    ckd_y,
    test_size=0.20,
    random_state=42,
    stratify=ckd_y
)

# Baseline Models

In [13]:
models = {
    "Majority Dummy": DummyClassifier(strategy="most_frequent"),

    "Stratified Dummy": DummyClassifier(strategy="stratified",
                                        random_state=42),

    "Logistic Regression":
        LogisticRegression(max_iter=1000,
                           random_state=42),

    "Decision Tree":
        DecisionTreeClassifier(random_state=42),

    "Random Forest":
        RandomForestClassifier(random_state=42),

    "XGBoost":
        XGBClassifier(
            eval_metric="logloss",
            random_state=42
        ),

    "LightGBM":
        LGBMClassifier(verbose=-1, random_state=42),

    "CatBoost":
        CatBoostClassifier(
            verbose=0,
            random_state=42
        ),

    "SVM":
        SVC(probability=True, kernel='rbf',
            random_state=42),

    "MLP":
        MLPClassifier(
            max_iter=500,
            random_state=42
        )
}

# Evaluation Function

In [14]:
def evaluate_model(model, X_train, X_test, y_train, y_test):

    model.fit(X_train, y_train)

    predictions = model.predict(X_test)

    probabilities = model.predict_proba(X_test)[:,1]

    tn, fp, fn, tp = confusion_matrix(
        y_test,
        predictions
    ).ravel()

    specificity = tn / (tn + fp)

    results = {

        "Accuracy":
            accuracy_score(y_test, predictions),

        "ROC AUC":
            roc_auc_score(y_test, probabilities),

        "PR AUC":
            average_precision_score(y_test, probabilities),

        "F1":
            f1_score(y_test, predictions),

        "MCC":
            matthews_corrcoef(y_test, predictions),

        "Sensitivity":
            recall_score(y_test, predictions),

        "Specificity":
            specificity,

        "Balanced Accuracy":
            balanced_accuracy_score(
                y_test,
                predictions
            ),

        "Brier Score":
            brier_score_loss(
                y_test,
                probabilities
            )
    }

    return results

# Train Every Model for CKD

In [15]:
ckd_results = []

for name, model in models.items():

    print(name)

    scores = evaluate_model(
        model,
        ckd_X_train,
        ckd_X_test,
        ckd_y_train,
        ckd_y_test
    )

    scores["Model"] = name

    ckd_results.append(scores)

Majority Dummy
Stratified Dummy
Logistic Regression
Decision Tree
Random Forest
XGBoost
LightGBM
CatBoost
SVM
MLP

# CKD Results DF

In [16]:
ckd_results_df = pd.DataFrame(ckd_results)

ckd_results_df = ckd_results_df[
    [
        "Model",
        "Accuracy",
        "ROC AUC",
        "PR AUC",
        "F1",
        "MCC",
        "Sensitivity",
        "Specificity",
        "Balanced Accuracy",
        "Brier Score"
    ]
]

ckd_results_df.sort_values(
    by="ROC AUC",
    ascending=False
)

                 Model  Accuracy  ...  Balanced Accuracy  Brier Score
7             CatBoost  0.934211  ...           0.918155     0.042829
2  Logistic Regression  0.934211  ...           0.925595     0.044095
6             LightGBM  0.960526  ...           0.946429     0.036906
4        Random Forest  0.947368  ...           0.936012     0.051782
5              XGBoost  0.934211  ...           0.910714     0.045096
9                  MLP  0.947368  ...           0.943452     0.048315
3        Decision Tree  0.907895  ...           0.889881     0.092105
8                  SVM  0.750000  ...           0.660714     0.147886
1     Stratified Dummy  0.592105  ...           0.550595     0.407895
0       Majority Dummy  0.631579  ...           0.500000     0.368421

[10 rows x 10 columns]

# Save CKD Results

In [17]:
ckd_results_df.to_csv(
    "CKD_Dataset_Baseline_Results.csv",
    index=False
)

# Load and Split dataset into train and test set

In [50]:
import pandas as pd

d_ckd_df = pd.read_csv("/content/DiabeticCKD_preprocessed.csv")

groups_df = pd.read_csv("/content/Patient_Groups.csv")

In [51]:
d_ckd_df.columns

Index(['Gender', 'Job', 'Family_Background_of_Diabetes', 'Diabetic_Year',
       'Age', 'Follow_suggested_Diet', 'Take_Medicine_for_Diabetes',
       'Take_Insulin', 'Hypertension', 'Heart_Disease', 'Sleep',
       'Water_Consumption', 'Smoke', 'Zarda_Betel_Leaf', 'Walk_Regularly',
       'Urination_Properly', 'Urinary_Infection', 'Pain_killer',
       'Calorie_Intake', 'CKD', 'Current_BMI'],
      dtype='object')

In [52]:
groups = groups_df["Patient_ID"]

In [53]:
d_ckd_X = d_ckd_df.drop(columns=["CKD"])
d_ckd_y = d_ckd_df["CKD"]

In [60]:
from sklearn.model_selection import GroupShuffleSplit

gss = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_idx, test_idx = next(
    gss.split(
        d_ckd_X,
        d_ckd_y,
        groups=groups
    )
)

d_ckd_X_train = d_ckd_X.iloc[train_idx]
d_ckd_X_test = d_ckd_X.iloc[test_idx]

d_ckd_y_train = d_ckd_y.iloc[train_idx]
d_ckd_y_test = d_ckd_y.iloc[test_idx]

# Verify the split

In [55]:
train_groups = set(groups.iloc[train_idx])
test_groups = set(groups.iloc[test_idx])

print(len(train_groups & test_groups))

0

# Train Every Model for Diabetic CKD

In [56]:
d_ckd_results = []

for name, model in models.items():

    print(name)

    scores = evaluate_model(
        model,
        d_ckd_X_train,
        d_ckd_X_test,
        d_ckd_y_train,
        d_ckd_y_test
    )

    scores["Model"] = name

    d_ckd_results.append(scores)

Majority Dummy
Stratified Dummy
Logistic Regression

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Decision Tree
Random Forest
XGBoost
LightGBM
CatBoost
SVM
MLP

# Diabetic CKD Results DF

In [57]:
d_ckd_results_df = pd.DataFrame(d_ckd_results)

d_ckd_results_df = d_ckd_results_df[
    [
        "Model",
        "Accuracy",
        "ROC AUC",
        "PR AUC",
        "F1",
        "MCC",
        "Sensitivity",
        "Specificity",
        "Balanced Accuracy",
        "Brier Score"
    ]
]

d_ckd_results_df.sort_values(
    by="ROC AUC",
    ascending=False
)

                 Model  Accuracy  ...  Balanced Accuracy  Brier Score
6             LightGBM   0.90875  ...           0.523514     0.077308
7             CatBoost   0.91375  ...           0.519687     0.077721
5              XGBoost   0.89250  ...           0.521184     0.085268
4        Random Forest   0.91250  ...           0.499316     0.078651
2  Logistic Regression   0.91375  ...           0.500000     0.076467
9                  MLP   0.91375  ...           0.500000     0.090542
1     Stratified Dummy   0.83625  ...           0.523216     0.163750
3        Decision Tree   0.83000  ...           0.513234     0.170000
0       Majority Dummy   0.91375  ...           0.500000     0.086250
8                  SVM   0.91375  ...           0.500000     0.079200

[10 rows x 10 columns]

# Save Diabetic CKD Results

In [58]:
d_ckd_results_df.to_csv(
    "Diabetic_CKD_Dataset_Baseline_Results.csv",
    index=False
)

# Additional Baseline

In [61]:
baseline_features = [
    "Age",
    "Diabetic_Year"
]

d_ckd_X_baseline = d_ckd_df[baseline_features]

d_ckd_X_train_baseline = d_ckd_X_baseline.iloc[train_idx]
d_ckd_X_test_baseline = d_ckd_X_baseline.iloc[test_idx]

d_ckd_y_train_baseline = d_ckd_y.iloc[train_idx]
d_ckd_y_test_baseline = d_ckd_y.iloc[test_idx]

In [62]:
baseline_model = LogisticRegression(max_iter=1000, random_state=42)

baseline_model.fit(d_ckd_X_train_baseline, d_ckd_y_train_baseline)

LogisticRegression(max_iter=1000, random_state=42)

In [63]:
add_base_score = evaluate_model(
    baseline_model,
    d_ckd_X_train_baseline,
    d_ckd_X_test_baseline,
    d_ckd_y_train_baseline,
    d_ckd_y_test_baseline
    )

In [64]:
add_base_score

{'Accuracy': 0.91375,
 'ROC AUC': np.float64(0.6086758262455639),
 'PR AUC': np.float64(0.10797011208537255),
 'F1': 0.0,
 'MCC': 0.0,
 'Sensitivity': 0.0,
 'Specificity': np.float64(1.0),
 'Balanced Accuracy': np.float64(0.5),
 'Brier Score': np.float64(0.07893997072867796)}