# Importing Libraries

In [12]:
!pip install fg-data-profiling

Requirement already satisfied: fg-data-profiling in /usr/local/lib/python3.12/dist-packages (4.19.1)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.13.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /usr/local/lib/python3.12/dist-packages (from visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.0.2)
Requirement already satisfied: minify-html>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (4.5.2)
Requirement already satisfied: imagehash==4.3.2 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->fg-data-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->fg-data-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->fg-data-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->fg-data-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2026.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->fg-data-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (2026.6.17)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->fg-data-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (3.6.1)
Requirement already satisfied: puremagic in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->fg-data-profiling) (1.17.0)

In [13]:
import pandas as pd
import numpy as np
from data_profiling import ProfileReport

#Dataset: Diabetic_CKD_Dataset

In [14]:
df = pd.read_csv("/content/DiabeticCKD_dataset.csv")

df.head()

,Patient ID,"Gender (M-male, F-female)","Job (1-normal, 2-intermediate, 3-heavy)","Family Background of Diabetes (1-yes, 0-no)",Height (cm),Diabetic Year,Age,Average Age,Weight (kg),Average Weight (kg),...,"Sleep (1-sufficient, 0-insufficient)","Water Consumption (1-sufficient, 0-insufficient)","Smoke (1-yes, 0-no)","Zarda, Betel Leaf (1-yes, 0-no)","Walk Regularly (1-yes, 0-no)","Urination Properly (1-yes, 0-no)","Urinary Infection (1-yes, 0-no)","Pain killer (1-yes, 0-no)",Calorie Intake (per day),"CKD (1-yes, 0-no)"
0,1,F,1,0,158.5,1,48,53,49,49.5,...,0,1,0,0,0,1,0,1,1800,0
1,1,F,1,0,158.5,2,49,53,49,49.5,...,0,1,0,0,0,1,0,1,1800,0
2,1,F,1,0,158.5,3,50,53,49,49.5,...,0,1,0,0,0,1,0,1,1800,0
3,1,F,1,0,158.5,4,51,53,50,49.5,...,0,1,0,0,0,1,0,1,1800,0
4,1,F,1,0,158.5,5,52,53,49,49.5,...,0,1,0,0,0,1,0,1,1800,0

In [15]:
df.tail()

,Patient ID,"Gender (M-male, F-female)","Job (1-normal, 2-intermediate, 3-heavy)","Family Background of Diabetes (1-yes, 0-no)",Height (cm),Diabetic Year,Age,Average Age,Weight (kg),Average Weight (kg),...,"Sleep (1-sufficient, 0-insufficient)","Water Consumption (1-sufficient, 0-insufficient)","Smoke (1-yes, 0-no)","Zarda, Betel Leaf (1-yes, 0-no)","Walk Regularly (1-yes, 0-no)","Urination Properly (1-yes, 0-no)","Urinary Infection (1-yes, 0-no)","Pain killer (1-yes, 0-no)",Calorie Intake (per day),"CKD (1-yes, 0-no)"
3995,400,F,1,1,152.4,6,47,47,62,62.5,...,1,0,0,0,0,1,1,0,1500,1
3996,400,F,1,1,152.4,7,48,47,61,62.5,...,1,0,0,0,0,1,1,0,1500,1
3997,400,F,1,1,152.4,8,49,47,62,62.5,...,1,0,0,0,0,1,1,0,1500,1
3998,400,F,1,1,152.4,9,50,47,63,62.5,...,1,0,0,0,0,1,1,0,1500,1
3999,400,F,1,1,152.4,10,51,47,62,62.5,...,1,0,0,0,0,1,1,0,1500,1

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 26 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Patient ID                                        4000 non-null   int64
 1   Gender (M-male, F-female)                         4000 non-null   object
 2   Job (1-normal, 2-intermediate, 3-heavy)           4000 non-null   int64
 3   Family Background of Diabetes (1-yes, 0-no)       4000 non-null   int64
 4   Height (cm)                                       4000 non-null   float64
 5   Diabetic Year                                     4000 non-null   int64
 6   Age                                               4000 non-null   int64
 7   Average Age                                       4000 non-null   int64
 8   Weight (kg)                                       4000 non-null   int64
 9   Average Weight (kg)                               4000 non-null   float64
 10  BMI                                               4000 non-null   float64
 11  Follow suggested Diet (1-yes, 0-no)               4000 non-null   int64
 12  Take Medicine for Diabetes (1-yes, 0-no)          4000 non-null   int64
 13  Take Insulin (1-yes, 0-no)                        4000 non-null   int64
 14  Hypertension (1-yes, 0-no)                        4000 non-null   int64
 15  Heart Disease (1-yes, 0-no)                       4000 non-null   int64
 16  Sleep (1-sufficient, 0-insufficient)              4000 non-null   int64
 17  Water Consumption (1-sufficient, 0-insufficient)  4000 non-null   int64
 18  Smoke (1-yes, 0-no)                               4000 non-null   int64
 19  Zarda, Betel Leaf (1-yes, 0-no)                   4000 non-null   int64
 20  Walk Regularly (1-yes, 0-no)                      4000 non-null   int64
 21  Urination Properly (1-yes, 0-no)                  4000 non-null   int64
 22  Urinary Infection (1-yes, 0-no)                   4000 non-null   int64
 23  Pain killer (1-yes, 0-no)                         4000 non-null   int64
 24  Calorie Intake (per day)                          4000 non-null   int64
 25  CKD (1-yes, 0-no)                                 4000 non-null   int64
dtypes: float64(3), int64(22), object(1)
memory usage: 812.6+ KB

In [17]:
df.describe()

,Patient ID,"Job (1-normal, 2-intermediate, 3-heavy)","Family Background of Diabetes (1-yes, 0-no)",Height (cm),Diabetic Year,Age,Average Age,Weight (kg),Average Weight (kg),BMI,...,"Sleep (1-sufficient, 0-insufficient)","Water Consumption (1-sufficient, 0-insufficient)","Smoke (1-yes, 0-no)","Zarda, Betel Leaf (1-yes, 0-no)","Walk Regularly (1-yes, 0-no)","Urination Properly (1-yes, 0-no)","Urinary Infection (1-yes, 0-no)","Pain killer (1-yes, 0-no)",Calorie Intake (per day),"CKD (1-yes, 0-no)"
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,...,4000.00000,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,200.500000,1.281000,0.422500,158.295700,9.267500,50.875250,51.370000,61.530000,61.530000,24.590650,...,0.58725,0.91075,0.136500,0.248250,0.635750,0.852000,0.236750,0.293750,1453.700000,0.096500
std,115.484129,0.597602,0.494019,7.958838,6.483745,10.952085,10.568397,9.907252,9.745365,3.773854,...,0.49239,0.28514,0.343362,0.432052,0.481279,0.355144,0.425141,0.455536,211.552591,0.295313
min,1.000000,1.000000,0.000000,132.080000,1.000000,16.000000,21.000000,30.000000,31.500000,13.560000,...,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1000.000000,0.000000
25%,100.750000,1.000000,0.000000,152.400000,5.000000,44.000000,45.000000,55.000000,54.500000,22.200000,...,0.00000,1.00000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1300.000000,0.000000
50%,200.500000,1.000000,0.000000,157.480000,8.000000,51.000000,51.000000,62.000000,61.450000,24.455000,...,1.00000,1.00000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1400.000000,0.000000
75%,300.250000,1.000000,1.000000,164.000000,12.000000,58.000000,58.000000,68.000000,67.750000,26.767500,...,1.00000,1.00000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1500.000000,0.000000
max,400.000000,3.000000,1.000000,182.880000,41.000000,89.000000,85.000000,93.000000,90.000000,41.660000,...,1.00000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2400.000000,1.000000

In [18]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
3995    False
3996    False
3997    False
3998    False
3999    False
Length: 4000, dtype: bool

In [19]:
df.shape

(4000, 26)

In [20]:
df.columns.tolist()

['Patient ID',
 'Gender (M-male, F-female)',
 'Job (1-normal, 2-intermediate, 3-heavy)',
 'Family Background of Diabetes (1-yes, 0-no)',
 'Height (cm)',
 'Diabetic Year',
 'Age',
 'Average Age',
 'Weight (kg)',
 'Average Weight (kg)',
 'BMI',
 'Follow suggested Diet (1-yes, 0-no)',
 'Take Medicine for Diabetes (1-yes, 0-no)',
 'Take Insulin (1-yes, 0-no)',
 'Hypertension (1-yes, 0-no)',
 'Heart Disease (1-yes, 0-no)',
 'Sleep (1-sufficient, 0-insufficient)',
 'Water Consumption (1-sufficient, 0-insufficient)',
 'Smoke (1-yes, 0-no)',
 'Zarda, Betel Leaf (1-yes, 0-no)',
 'Walk Regularly (1-yes, 0-no)',
 'Urination Properly (1-yes, 0-no)',
 'Urinary Infection (1-yes, 0-no)',
 'Pain killer (1-yes, 0-no)',
 'Calorie Intake (per day)',
 'CKD (1-yes, 0-no)']

In [21]:
df_report = ProfileReport(df, title="Exploratory Data Analysis of Diabetic CKD Dataset")

In [ ]:
df_report.to_file("diabetic_ckd_dataset_summary.html")