# Importing Libraries

In [1]:
!pip install fg-data-profiling

Collecting fg-data-profiling
  Downloading fg_data_profiling-4.19.1-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.0.2)
Collecting minify-html>=0.15.0 (from fg-data-profiling)
  Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from fg-data-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from fg-data-profiling)
  Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from fg-data-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (4.5.2)
Collecting imagehash==4.3.2 (from fg-data-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from fg-data-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->fg-data-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->fg-data-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->fg-data-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->fg-data-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2026.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->fg-data-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (2026.5.20)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->fg-data-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->fg-data-profiling) (1.17.0)
Downloading fg_data_profiling-4.19.1-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.3/400.3 kB 911.3 kB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 5.1 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 8.5 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 25.2 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 6.9 MB/s eta 0:00:00
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 5.2 MB/s eta 0:00:00
Installing collected packages: minify-html, filetype, puremagic, multimethod, dacite, imagehash, visions, phik, fg-data-profiling
Successfully installed dacite-1.9.2 fg-data-profiling-4.19.1 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.2.0 visions-0.8.1

In [2]:
import pandas as pd
import numpy as np
from data_profiling import ProfileReport

#Dataset: CKD_Dataset

In [3]:
df = pd.read_excel("/content/CKD_dataset.xlsx")

df.head()

,p_id,age,gender,u_clarity,ph,sp_g,albumin,glucose,sugar,kb,...,blood,pus_cells,red_cells,epi_cells,mt,co,gc,bacteria,cc,d_status
0,1,28,male,p.yellow,5.0,1.010,trace,nill,nill,not_trace,...,negative,normal,normal,nill,none,positive,seen,notseen,notfound,notckd
1,2,43,female,yellow,5.5,1.020,trace,nill,positive,not_trace,...,negative,abnormal,abnormal,positive,present,nill,nill,seen,notfound,ckd
2,3,32,female,p.yellow,5.0,1.010,nill,nill,nill,not_trace,...,negative,normal,normal,nill,none,nill,nill,notseen,notfound,notckd
3,4,64,female,yellow,5.0,1.015,trace,nill,nill,not_trace,...,negative,abnormal,abnormal,positive,present,positive,nill,seen,found,ckd
4,5,37,male,p.yellow,5.0,1.010,nill,nill,nill,not_trace,...,negative,normal,normal,nill,none,nill,nill,notseen,notfound,notckd

In [13]:
df.tail()

,p_id,age,gender,u_clarity,ph,sp_g,albumin,glucose,sugar,kb,...,blood,pus_cells,red_cells,epi_cells,mt,co,gc,bacteria,cc,d_status
375,376,52,female,yellow,5.0,1.025,trace,positive,nill,not_trace,...,negative,abnormal,normal,positive,present,nill,nill,notseen,notfound,ckd
376,377,67,female,yellow,5.0,1.025,trace,positive,nill,not_trace,...,negative,abnormal,normal,positive,none,nill,nill,notseen,notfound,ckd
377,378,41,female,yellow,5.0,1.020,nill,nill,nill,not_trace,...,negative,normal,normal,nill,present,nill,nill,notseen,notfound,notckd
378,379,63,female,yellow,6.0,1.020,trace,positive,nill,not_trace,...,negative,abnormal,abnormal,positive,present,nill,nill,seen,notfound,ckd
379,380,38,female,yellow,5.5,1.020,trace,nill,nill,not_trace,...,negative,normal,normal,positive,present,positive,nill,notseen,notfound,notckd

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 22 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   p_id       380 non-null    int64
 1   age        380 non-null    int64
 2   gender     380 non-null    object
 3   u_clarity  380 non-null    object
 4   ph         380 non-null    float64
 5   sp_g       380 non-null    float64
 6   albumin    380 non-null    object
 7   glucose    380 non-null    object
 8   sugar      380 non-null    object
 9   kb         380 non-null    object
 10  bpigment   380 non-null    object
 11  ur_bi      380 non-null    object
 12  blood      380 non-null    object
 13  pus_cells  380 non-null    object
 14  red_cells  380 non-null    object
 15  epi_cells  380 non-null    object
 16  mt         380 non-null    object
 17  co         380 non-null    object
 18  gc         380 non-null    object
 19  bacteria   380 non-null    object
 20  cc         380 non-null    object
 21  d_status   380 non-null    object
dtypes: float64(2), int64(2), object(18)
memory usage: 65.4+ KB

In [11]:
df.describe()

             p_id         age          ph        sp_g
count  380.000000  380.000000  380.000000  380.000000
mean   190.500000   44.760526    5.565000    1.015934
std    109.840794   15.852653    0.561482    0.005262
min      1.000000   12.000000    5.000000    1.000000
25%     95.750000   32.000000    5.000000    1.010000
50%    190.500000   44.000000    5.500000    1.020000
75%    285.250000   56.000000    6.000000    1.020000
max    380.000000   91.000000    8.000000    1.050000

In [16]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
375    False
376    False
377    False
378    False
379    False
Length: 380, dtype: bool

In [9]:
df.shape

(380, 22)

In [10]:
df.columns.tolist()

['p_id',
 'age',
 'gender',
 'u_clarity',
 'ph',
 'sp_g',
 'albumin',
 'glucose',
 'sugar',
 'kb',
 'bpigment',
 'ur_bi',
 'blood',
 'pus_cells',
 'red_cells',
 'epi_cells',
 'mt',
 'co',
 'gc',
 'bacteria',
 'cc',
 'd_status']

In [8]:
df_report = ProfileReport(df, title="Exploratory Data Analysis of CKD Dataset")

In [6]:
df_report.to_file("ckd_dataset_summary.html")

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]