# Importing Libraries

In [28]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

#Dataset-1: CKD_Dataset

In [29]:
df1 = pd.read_excel("/content/CKD_dataset.xlsx")
df1.head()

   p_id  age  gender u_clarity   ph  ...        co    gc bacteria        cc d_status
0     1   28    male  p.yellow  5.0  ...  positive  seen  notseen  notfound   notckd
1     2   43  female    yellow  5.5  ...      nill  nill     seen  notfound      ckd
2     3   32  female  p.yellow  5.0  ...      nill  nill  notseen  notfound   notckd
3     4   64  female    yellow  5.0  ...  positive  nill     seen     found      ckd
4     5   37    male  p.yellow  5.0  ...      nill  nill  notseen  notfound   notckd

[5 rows x 22 columns]

In [30]:
df1 = df1.drop(columns=["p_id"])

df1_X = df1.drop(columns=["d_status"])
df1_y = df1["d_status"]

In [31]:
print(df1.duplicated().sum())

7

In [32]:
df1 = df1.drop_duplicates()

In [33]:
missing = df1.isnull().sum()

print(missing[missing > 0])

Series([], dtype: int64)

In [34]:
print(df1_y.value_counts())
print(df1_y.unique())

d_status
ckd       239
notckd    141
Name: count, dtype: int64
['notckd' 'ckd']

In [35]:
cat_columns = df1_X.select_dtypes('object').columns

for col in cat_columns:
  df1_X[col] = df1_X[col].astype(str).str.strip().str.lower()
  print(f"{col}: {df1_X[col].unique()}")

gender: ['male' 'female']
u_clarity: ['p.yellow' 'yellow']
albumin: ['trace' 'nill']
glucose: ['nill' 'positive']
sugar: ['nill' 'positive']
kb: ['not_trace' 'trace']
bpigment: ['absent' 'present']
ur_bi: ['normal' 'abnormal']
blood: ['negative' 'positive']
pus_cells: ['normal' 'abnormal']
red_cells: ['normal' 'abnormal']
epi_cells: ['nill' 'positive']
mt: ['none' 'present']
co: ['positive' 'nill']
gc: ['seen' 'nill']
bacteria: ['notseen' 'seen']
cc: ['notfound' 'found']

In [36]:
print(f"d_status: {df1_y.unique()}")

d_status: ['notckd' 'ckd']

In [37]:
oe = OrdinalEncoder()
df1_X = pd.DataFrame(oe.fit_transform(df1_X), columns=df1_X.columns)

In [38]:
df1_y = df1_y.map({
    'notckd': 0,
    'ckd': 1
})

In [39]:
for col in cat_columns:
  print(f"{col}: {df1_X[col].unique()}")

gender: [1. 0.]
u_clarity: [0. 1.]
albumin: [1. 0.]
glucose: [0. 1.]
sugar: [0. 1.]
kb: [0. 1.]
bpigment: [0. 1.]
ur_bi: [1. 0.]
blood: [0. 1.]
pus_cells: [1. 0.]
red_cells: [1. 0.]
epi_cells: [0. 1.]
mt: [0. 1.]
co: [1. 0.]
gc: [1. 0.]
bacteria: [0. 1.]
cc: [1. 0.]

In [40]:
print(f"d_status: {df1_y.unique()}")

d_status: [0 1]

In [41]:
continuous = [
    "age",
    "ph",
    "sp_g"
]

df1_X[continuous] = df1_X[continuous].apply(pd.to_numeric)

In [42]:
df1_clean = pd.concat([df1_X, df1_y], axis=1)

In [43]:
df1_clean.to_csv(
    "CKD_preprocessed.csv",
    index=False
)

#Dataset-2: Diabetic_CKD_Dataset

In [45]:
df2 = pd.read_csv("/content/DiabeticCKD_dataset.csv")
df2.head()

   Patient ID  ... CKD (1-yes, 0-no)
0           1  ...                 0
1           1  ...                 0
2           1  ...                 0
3           1  ...                 0
4           1  ...                 0

[5 rows x 26 columns]

In [50]:
df2.columns.to_list()

['Patient ID',
 'Gender (M-male, F-female)',
 'Job (1-normal, 2-intermediate, 3-heavy)',
 'Family Background of Diabetes (1-yes, 0-no)',
 'Height (cm)',
 'Diabetic Year',
 'Age',
 'Average Age',
 'Weight (kg)',
 'Average Weight (kg)',
 'BMI',
 'Follow suggested Diet (1-yes, 0-no)',
 'Take Medicine for Diabetes (1-yes, 0-no)',
 'Take Insulin (1-yes, 0-no)',
 'Hypertension (1-yes, 0-no)',
 'Heart Disease (1-yes, 0-no)',
 'Sleep (1-sufficient, 0-insufficient)',
 'Water Consumption (1-sufficient, 0-insufficient)',
 'Smoke (1-yes, 0-no)',
 'Zarda, Betel Leaf (1-yes, 0-no)',
 'Walk Regularly (1-yes, 0-no)',
 'Urination Properly (1-yes, 0-no)',
 'Urinary Infection (1-yes, 0-no)',
 'Pain killer (1-yes, 0-no)',
 'Calorie Intake (per day)',
 'CKD (1-yes, 0-no)']

In [47]:
groups = df2['Patient ID']

In [51]:
df2 = df2.drop(columns=[
    "Patient ID",
    "Average Age",
    "Average Weight (kg)",
    "BMI"
])

In [53]:
df2["Current_BMI"] = (
    df2["Weight (kg)"] /
    (df2["Height (cm)"]/100)**2
)

In [55]:
df2 = df2.drop(columns=[
    "Height (cm)",
    "Weight (kg)"
])

In [56]:
print(df2.duplicated().sum())

7

In [57]:
df2 = df2.drop_duplicates()

In [58]:
missing = df2.isnull().sum()

print(missing[missing > 0])

Series([], dtype: int64)

In [59]:
df2.select_dtypes(include='object').columns

Index(['Gender (M-male, F-female)'], dtype='object')

In [62]:
df2['Gender (M-male, F-female)'].unique()

array(['F', 'M'], dtype=object)

In [63]:
df2['Gender (M-male, F-female)'] = df2['Gender (M-male, F-female)'].map({
    'F': 0,
    'M': 1
})

In [65]:
df2.to_csv(
    "DiabeticCKD_preprocessed.csv",
    index=False)

In [66]:
groups.to_csv(
    "Patient_Groups.csv",
    index=False
)